apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-pod
spec:
   replicas: 1 
   selector:
    matchLabels:
     component: web
   template:
     metadata:
       labels:
        component: web
     spec:
        containers:
         - name: client
           image: nginx
           ports:
            - containerPort: 3000
